# Copyright 2019 IBM Corporation All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

language: bash
dist: xenial
services:
- docker
#Builds the docker image for the service
install:
- make build
#Run Test.
script:
- echo "Run tests here"
#Pushes image to registry and deploys it to dev environment for testing.
#We execute this only if this is tagged release
deploy:
#Execute block only on master
- provider: script
  script: make release-if-not-auto-push
  skip_cleanup: true
  on:
    branch: master

#Execute block on tagged release.
- provider: script
  script: make push
  skip_cleanup: true
  on:
    tags: true
    condition: ${TRAVIS_TAG} =~ ^[0-9]+\.[0-9]+\.[0-9]+.*$

env:
  global:
#Docker registry token
  - DOCKER_REGISTRY_URL="de.icr.io"
